### ISSUE TITLE
Profile cannot access local variable 'html' where it is not associated with a value

### ISSUE THREAD

**Issue by mqllin** [n0madic/twitter-scraper#120]
```python
import requests
from twitter_scraper import Profile

# Set up proxies
proxies = {
  'http': 'http://127.0.0.1:7890',
  'https': 'http://127.0.0.1:7890',
}

# Set the proxies for requests
requests.session().proxies = proxies

if __name__ == '__main__':
    profile = Profile("LaHo44646318")
    print(profile.to_dict())
```

Profile cannot access local variable 'html' where it is not associated with a value
```
Traceback (most recent call last):
  File "/Users/mql/Documents/Project/临时测试目录/pythonProject/twAPI/api.py", line 14, in <module>
    profile = Profile("LaHo44646318")
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/twitter_scraper-0.4.3-py3.11.egg/twitter_scraper/modules/profile.py", line 41, in __init__
    class _Utils:
            ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/twitter_scraper-0.4.3-py3.11.egg/twitter_scraper/modules/profile.py", line 65, in __parse_profile
    finally:
             
UnboundLocalError: cannot access local variable 'html' where it is not associated with a value

```
Is the twitter_scraper still usable?

**Comment by n0madic** [comment]
It's Golang library, no Python...
may be this https://github.com/bisguzar/twitter-scraper ?
